#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

./script/bootstrap

echo "==> Setting up DB…"

if command -v docker-compose >/dev/null 2>&1; then
  docker-compose run web bash -c "bundle exec hanami db migrate"
else
  echo "==> Please install docker first"
fi




