#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

echo "==> Running tests…"

if command -v docker-compose >/dev/null 2>&1; then
  if [ -n "$1" ]; then
    docker-compose run web rspec spec "$1"
  else
    docker-compose run web rspec spec
  fi
else
  echo "==> Please install docker first"
fi
